//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.8.3928.0.
// 


/// <remarks/>
// CODEGEN: 'http://schemas.xmlsoap.org/ws/2004/09/policy' ad alanındaki 'Policy' isteğe bağlı WSDL uzantı öğesi işlenmedi.
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="ZAPP_EBA_FI_DV_GONDER", Namespace="urn:sap-com:document:sap:rfc:functions")]
public partial class ZAPP_EBA_FI_DV_GONDER : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback CallZAPP_EBA_FI_DV_GONDEROperationCompleted;
    
    /// <remarks/>
    public ZAPP_EBA_FI_DV_GONDER() {
        this.Url = "http://SMPERPPRDA1.sampadc.local:8000/sap/bc/srt/rfc/sap/zapp_eba_fi_dv_gonder/40" +
            "0/zapp_eba_fi_dv_gonder/zapp_eba_fi_dv_gonder";
    }
    
    /// <remarks/>
    public event CallZAPP_EBA_FI_DV_GONDERCompletedEventHandler CallZAPP_EBA_FI_DV_GONDERCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:rfc:functions:ZAPP_EBA_FI_DV_GONDER:ZAPP_EBA_FI_DV_GONDE" +
        "RRequest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("ZAPP_EBA_FI_DV_GONDERResponse", Namespace="urn:sap-com:document:sap:rfc:functions")]
    public ZAPP_EBA_FI_DV_GONDERResponse CallZAPP_EBA_FI_DV_GONDER([System.Xml.Serialization.XmlElementAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")] ZAPP_EBA_FI_DV_GONDER1 ZAPP_EBA_FI_DV_GONDER) {
        object[] results = this.Invoke("CallZAPP_EBA_FI_DV_GONDER", new object[] {
                    ZAPP_EBA_FI_DV_GONDER});
        return ((ZAPP_EBA_FI_DV_GONDERResponse)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginCallZAPP_EBA_FI_DV_GONDER(ZAPP_EBA_FI_DV_GONDER1 ZAPP_EBA_FI_DV_GONDER, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("CallZAPP_EBA_FI_DV_GONDER", new object[] {
                    ZAPP_EBA_FI_DV_GONDER}, callback, asyncState);
    }
    
    /// <remarks/>
    public ZAPP_EBA_FI_DV_GONDERResponse EndCallZAPP_EBA_FI_DV_GONDER(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((ZAPP_EBA_FI_DV_GONDERResponse)(results[0]));
    }
    
    /// <remarks/>
    public void CallZAPP_EBA_FI_DV_GONDERAsync(ZAPP_EBA_FI_DV_GONDER1 ZAPP_EBA_FI_DV_GONDER) {
        this.CallZAPP_EBA_FI_DV_GONDERAsync(ZAPP_EBA_FI_DV_GONDER, null);
    }
    
    /// <remarks/>
    public void CallZAPP_EBA_FI_DV_GONDERAsync(ZAPP_EBA_FI_DV_GONDER1 ZAPP_EBA_FI_DV_GONDER, object userState) {
        if ((this.CallZAPP_EBA_FI_DV_GONDEROperationCompleted == null)) {
            this.CallZAPP_EBA_FI_DV_GONDEROperationCompleted = new System.Threading.SendOrPostCallback(this.OnCallZAPP_EBA_FI_DV_GONDEROperationCompleted);
        }
        this.InvokeAsync("CallZAPP_EBA_FI_DV_GONDER", new object[] {
                    ZAPP_EBA_FI_DV_GONDER}, this.CallZAPP_EBA_FI_DV_GONDEROperationCompleted, userState);
    }
    
    private void OnCallZAPP_EBA_FI_DV_GONDEROperationCompleted(object arg) {
        if ((this.CallZAPP_EBA_FI_DV_GONDERCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.CallZAPP_EBA_FI_DV_GONDERCompleted(this, new CallZAPP_EBA_FI_DV_GONDERCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
public partial class ZAPP_EBA_FI_DV_GONDER1 {
    
    private ZAPP_EBA_DV[] lT_DVField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public ZAPP_EBA_DV[] LT_DV {
        get {
            return this.lT_DVField;
        }
        set {
            this.lT_DVField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
public partial class ZAPP_EBA_DV {
    
    private string bUKRSField;
    
    private string bUTXTField;
    
    private string aNLN1Field;
    
    private string aNLN2Field;
    
    private string tXT50Field;
    
    private string aKTIVField;
    
    private string kTOGRField;
    
    private string mEINSField;
    
    private decimal mENGEField;
    
    private string kTGRTXField;
    
    private string nDJARField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BUKRS {
        get {
            return this.bUKRSField;
        }
        set {
            this.bUKRSField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BUTXT {
        get {
            return this.bUTXTField;
        }
        set {
            this.bUTXTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ANLN1 {
        get {
            return this.aNLN1Field;
        }
        set {
            this.aNLN1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ANLN2 {
        get {
            return this.aNLN2Field;
        }
        set {
            this.aNLN2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TXT50 {
        get {
            return this.tXT50Field;
        }
        set {
            this.tXT50Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AKTIV {
        get {
            return this.aKTIVField;
        }
        set {
            this.aKTIVField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string KTOGR {
        get {
            return this.kTOGRField;
        }
        set {
            this.kTOGRField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MEINS {
        get {
            return this.mEINSField;
        }
        set {
            this.mEINSField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal MENGE {
        get {
            return this.mENGEField;
        }
        set {
            this.mENGEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string KTGRTX {
        get {
            return this.kTGRTXField;
        }
        set {
            this.kTGRTXField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NDJAR {
        get {
            return this.nDJARField;
        }
        set {
            this.nDJARField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
public partial class ZAPP_EBA_FI_DV_GONDERResponse {
    
    private ZAPP_EBA_DV[] lT_DVField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public ZAPP_EBA_DV[] LT_DV {
        get {
            return this.lT_DVField;
        }
        set {
            this.lT_DVField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
public delegate void CallZAPP_EBA_FI_DV_GONDERCompletedEventHandler(object sender, CallZAPP_EBA_FI_DV_GONDERCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CallZAPP_EBA_FI_DV_GONDERCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal CallZAPP_EBA_FI_DV_GONDERCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public ZAPP_EBA_FI_DV_GONDERResponse Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((ZAPP_EBA_FI_DV_GONDERResponse)(this.results[0]));
        }
    }
}
