//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.8.3928.0.
// 


/// <remarks/>
// CODEGEN: 'http://schemas.xmlsoap.org/ws/2004/09/policy' ad alanındaki 'Policy' isteğe bağlı WSDL uzantı öğesi işlenmedi.
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name = "ZAPP_EBA_FATURA_GONDER_RFC", Namespace = "urn:sap-com:document:sap:rfc:functions")]
public partial class ZAPP_EBA_FATURA_GONDER_RFC : System.Web.Services.Protocols.SoapHttpClientProtocol
{

    private System.Threading.SendOrPostCallback CallZAPP_EBA_FATURA_GONDER_RFCOperationCompleted;

    /// <remarks/>
    public ZAPP_EBA_FATURA_GONDER_RFC()
    {
        this.Url = "http://SMPERPPRDA1.sampadc.local:8000/sap/bc/srt/rfc/sap/zapp_eba_fatura_gonder_r" +
            "fc/400/zapp_eba_fatura_gonder_rfc/zapp_eba_fatura_gonder_rfc";
    }

    /// <remarks/>
    public event CallZAPP_EBA_FATURA_GONDER_RFCCompletedEventHandler CallZAPP_EBA_FATURA_GONDER_RFCCompleted;

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:rfc:functions:ZAPP_EBA_FATURA_GONDER_RFC:ZAPP_EBA_FATURA" +
        "_GONDER_RFCRequest", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("ZAPP_EBA_FATURA_GONDER_RFCResponse", Namespace = "urn:sap-com:document:sap:rfc:functions")]
    public ZAPP_EBA_FATURA_GONDER_RFCResponse CallZAPP_EBA_FATURA_GONDER_RFC([System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:sap-com:document:sap:rfc:functions")] ZAPP_EBA_FATURA_GONDER_RFC1 ZAPP_EBA_FATURA_GONDER_RFC)
    {
        object[] results = this.Invoke("CallZAPP_EBA_FATURA_GONDER_RFC", new object[] {
                    ZAPP_EBA_FATURA_GONDER_RFC});
        return ((ZAPP_EBA_FATURA_GONDER_RFCResponse)(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginCallZAPP_EBA_FATURA_GONDER_RFC(ZAPP_EBA_FATURA_GONDER_RFC1 ZAPP_EBA_FATURA_GONDER_RFC, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("CallZAPP_EBA_FATURA_GONDER_RFC", new object[] {
                    ZAPP_EBA_FATURA_GONDER_RFC}, callback, asyncState);
    }

    /// <remarks/>
    public ZAPP_EBA_FATURA_GONDER_RFCResponse EndCallZAPP_EBA_FATURA_GONDER_RFC(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((ZAPP_EBA_FATURA_GONDER_RFCResponse)(results[0]));
    }

    /// <remarks/>
    public void CallZAPP_EBA_FATURA_GONDER_RFCAsync(ZAPP_EBA_FATURA_GONDER_RFC1 ZAPP_EBA_FATURA_GONDER_RFC)
    {
        this.CallZAPP_EBA_FATURA_GONDER_RFCAsync(ZAPP_EBA_FATURA_GONDER_RFC, null);
    }

    /// <remarks/>
    public void CallZAPP_EBA_FATURA_GONDER_RFCAsync(ZAPP_EBA_FATURA_GONDER_RFC1 ZAPP_EBA_FATURA_GONDER_RFC, object userState)
    {
        if ((this.CallZAPP_EBA_FATURA_GONDER_RFCOperationCompleted == null))
        {
            this.CallZAPP_EBA_FATURA_GONDER_RFCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCallZAPP_EBA_FATURA_GONDER_RFCOperationCompleted);
        }
        this.InvokeAsync("CallZAPP_EBA_FATURA_GONDER_RFC", new object[] {
                    ZAPP_EBA_FATURA_GONDER_RFC}, this.CallZAPP_EBA_FATURA_GONDER_RFCOperationCompleted, userState);
    }

    private void OnCallZAPP_EBA_FATURA_GONDER_RFCOperationCompleted(object arg)
    {
        if ((this.CallZAPP_EBA_FATURA_GONDER_RFCCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.CallZAPP_EBA_FATURA_GONDER_RFCCompleted(this, new CallZAPP_EBA_FATURA_GONDER_RFCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    public new void CancelAsync(object userState)
    {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:sap-com:document:sap:rfc:functions")]
public partial class ZAPP_EBA_FATURA_GONDER_RFC1
{

    private ZEBA_INV_DETAIL[] eT_INVOICEField;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    public ZEBA_INV_DETAIL[] ET_INVOICE
    {
        get
        {
            return this.eT_INVOICEField;
        }
        set
        {
            this.eT_INVOICEField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:sap-com:document:sap:rfc:functions")]
public partial class ZEBA_INV_DETAIL
{

    private string mANDTField;

    private string idField;

    private string pRFIDField;

    private string iNVTYField;

    private string bUKRSField;

    private string vBELNField;

    private string fKDATField;

    private string zTERMField;

    private string sTCD3Field;

    private string fIRMA_KODField;

    private string fIRMA_ADField;

    private decimal tUTARField;

    private decimal kDVField;

    private string wAERSField;

    private decimal kURField;

    private string zNOTField;

    private string sICILField;

    private string sICIL_TNMField;

    private string zDDATA1Field;

    private string zDDATA2Field;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MANDT
    {
        get
        {
            return this.mANDTField;
        }
        set
        {
            this.mANDTField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ID
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PRFID
    {
        get
        {
            return this.pRFIDField;
        }
        set
        {
            this.pRFIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string INVTY
    {
        get
        {
            return this.iNVTYField;
        }
        set
        {
            this.iNVTYField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BUKRS
    {
        get
        {
            return this.bUKRSField;
        }
        set
        {
            this.bUKRSField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string VBELN
    {
        get
        {
            return this.vBELNField;
        }
        set
        {
            this.vBELNField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FKDAT
    {
        get
        {
            return this.fKDATField;
        }
        set
        {
            this.fKDATField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ZTERM
    {
        get
        {
            return this.zTERMField;
        }
        set
        {
            this.zTERMField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string STCD3
    {
        get
        {
            return this.sTCD3Field;
        }
        set
        {
            this.sTCD3Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FIRMA_KOD
    {
        get
        {
            return this.fIRMA_KODField;
        }
        set
        {
            this.fIRMA_KODField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FIRMA_AD
    {
        get
        {
            return this.fIRMA_ADField;
        }
        set
        {
            this.fIRMA_ADField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal TUTAR
    {
        get
        {
            return this.tUTARField;
        }
        set
        {
            this.tUTARField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal KDV
    {
        get
        {
            return this.kDVField;
        }
        set
        {
            this.kDVField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string WAERS
    {
        get
        {
            return this.wAERSField;
        }
        set
        {
            this.wAERSField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal KUR
    {
        get
        {
            return this.kURField;
        }
        set
        {
            this.kURField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ZNOT
    {
        get
        {
            return this.zNOTField;
        }
        set
        {
            this.zNOTField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SICIL
    {
        get
        {
            return this.sICILField;
        }
        set
        {
            this.sICILField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SICIL_TNM
    {
        get
        {
            return this.sICIL_TNMField;
        }
        set
        {
            this.sICIL_TNMField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ZDDATA1
    {
        get
        {
            return this.zDDATA1Field;
        }
        set
        {
            this.zDDATA1Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ZDDATA2
    {
        get
        {
            return this.zDDATA2Field;
        }
        set
        {
            this.zDDATA2Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:sap-com:document:sap:rfc:functions")]
public partial class ZAPP_EBA_FATURA_GONDER_RFCResponse
{

    private ZEBA_INV_DETAIL[] eT_INVOICEField;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    public ZEBA_INV_DETAIL[] ET_INVOICE
    {
        get
        {
            return this.eT_INVOICEField;
        }
        set
        {
            this.eT_INVOICEField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
public delegate void CallZAPP_EBA_FATURA_GONDER_RFCCompletedEventHandler(object sender, CallZAPP_EBA_FATURA_GONDER_RFCCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CallZAPP_EBA_FATURA_GONDER_RFCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal CallZAPP_EBA_FATURA_GONDER_RFCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public ZAPP_EBA_FATURA_GONDER_RFCResponse Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((ZAPP_EBA_FATURA_GONDER_RFCResponse)(this.results[0]));
        }
    }
}
