//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.8.3928.0.
// 


/// <remarks/>
// CODEGEN: 'http://schemas.xmlsoap.org/ws/2004/09/policy' ad alanındaki 'Policy' isteğe bağlı WSDL uzantı öğesi işlenmedi.
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name = "ZAPP_EBA_FATURA_PDF_GONDER_RFC", Namespace = "urn:sap-com:document:sap:rfc:functions")]
public partial class ZAPP_EBA_FATURA_PDF_GONDER_RFC : System.Web.Services.Protocols.SoapHttpClientProtocol
{

    private System.Threading.SendOrPostCallback CallZAPP_EBA_FATURA_PDF_GONDER_RFCOperationCompleted;

    /// <remarks/>
    public ZAPP_EBA_FATURA_PDF_GONDER_RFC()
    {
        this.Url = "http://SMPERPPRDA1.sampadc.local:8000/sap/bc/srt/rfc/sap/zapp_eba_fatura_pdf_gond" +
            "er_rfc/400/zapp_eba_fatura_pdf_gonder_rfc/zapp_eba_fatura_pdf_gonder_rfc";
    }

    /// <remarks/>
    public event CallZAPP_EBA_FATURA_PDF_GONDER_RFCCompletedEventHandler CallZAPP_EBA_FATURA_PDF_GONDER_RFCCompleted;

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:rfc:functions:ZAPP_EBA_FATURA_PDF_GONDER_RFC:ZAPP_EBA_FA" +
        "TURA_PDF_GONDER_RFCRequest", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("ZAPP_EBA_FATURA_PDF_GONDER_RFCResponse", Namespace = "urn:sap-com:document:sap:rfc:functions")]
    public ZAPP_EBA_FATURA_PDF_GONDER_RFCResponse CallZAPP_EBA_FATURA_PDF_GONDER_RFC([System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:sap-com:document:sap:rfc:functions")] ZAPP_EBA_FATURA_PDF_GONDER_RFC1 ZAPP_EBA_FATURA_PDF_GONDER_RFC)
    {
        object[] results = this.Invoke("CallZAPP_EBA_FATURA_PDF_GONDER_RFC", new object[] {
                    ZAPP_EBA_FATURA_PDF_GONDER_RFC});
        return ((ZAPP_EBA_FATURA_PDF_GONDER_RFCResponse)(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginCallZAPP_EBA_FATURA_PDF_GONDER_RFC(ZAPP_EBA_FATURA_PDF_GONDER_RFC1 ZAPP_EBA_FATURA_PDF_GONDER_RFC, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("CallZAPP_EBA_FATURA_PDF_GONDER_RFC", new object[] {
                    ZAPP_EBA_FATURA_PDF_GONDER_RFC}, callback, asyncState);
    }

    /// <remarks/>
    public ZAPP_EBA_FATURA_PDF_GONDER_RFCResponse EndCallZAPP_EBA_FATURA_PDF_GONDER_RFC(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((ZAPP_EBA_FATURA_PDF_GONDER_RFCResponse)(results[0]));
    }

    /// <remarks/>
    public void CallZAPP_EBA_FATURA_PDF_GONDER_RFCAsync(ZAPP_EBA_FATURA_PDF_GONDER_RFC1 ZAPP_EBA_FATURA_PDF_GONDER_RFC)
    {
        this.CallZAPP_EBA_FATURA_PDF_GONDER_RFCAsync(ZAPP_EBA_FATURA_PDF_GONDER_RFC, null);
    }

    /// <remarks/>
    public void CallZAPP_EBA_FATURA_PDF_GONDER_RFCAsync(ZAPP_EBA_FATURA_PDF_GONDER_RFC1 ZAPP_EBA_FATURA_PDF_GONDER_RFC, object userState)
    {
        if ((this.CallZAPP_EBA_FATURA_PDF_GONDER_RFCOperationCompleted == null))
        {
            this.CallZAPP_EBA_FATURA_PDF_GONDER_RFCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCallZAPP_EBA_FATURA_PDF_GONDER_RFCOperationCompleted);
        }
        this.InvokeAsync("CallZAPP_EBA_FATURA_PDF_GONDER_RFC", new object[] {
                    ZAPP_EBA_FATURA_PDF_GONDER_RFC}, this.CallZAPP_EBA_FATURA_PDF_GONDER_RFCOperationCompleted, userState);
    }

    private void OnCallZAPP_EBA_FATURA_PDF_GONDER_RFCOperationCompleted(object arg)
    {
        if ((this.CallZAPP_EBA_FATURA_PDF_GONDER_RFCCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.CallZAPP_EBA_FATURA_PDF_GONDER_RFCCompleted(this, new CallZAPP_EBA_FATURA_PDF_GONDER_RFCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    public new void CancelAsync(object userState)
    {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:sap-com:document:sap:rfc:functions")]
public partial class ZAPP_EBA_FATURA_PDF_GONDER_RFC1
{

    private string i_VBELNField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string I_VBELN
    {
        get
        {
            return this.i_VBELNField;
        }
        set
        {
            this.i_VBELNField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:sap-com:document:sap:rfc:functions")]
public partial class ZAPP_EBA_FATURA_PDF_GONDER_RFCResponse
{

    private string e_PDFField;

    private string e_VBELNField;

    private string e_XMLField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string E_PDF
    {
        get
        {
            return this.e_PDFField;
        }
        set
        {
            this.e_PDFField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string E_VBELN
    {
        get
        {
            return this.e_VBELNField;
        }
        set
        {
            this.e_VBELNField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string E_XML
    {
        get
        {
            return this.e_XMLField;
        }
        set
        {
            this.e_XMLField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
public delegate void CallZAPP_EBA_FATURA_PDF_GONDER_RFCCompletedEventHandler(object sender, CallZAPP_EBA_FATURA_PDF_GONDER_RFCCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CallZAPP_EBA_FATURA_PDF_GONDER_RFCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal CallZAPP_EBA_FATURA_PDF_GONDER_RFCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public ZAPP_EBA_FATURA_PDF_GONDER_RFCResponse Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((ZAPP_EBA_FATURA_PDF_GONDER_RFCResponse)(this.results[0]));
        }
    }
}
