//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.8.3928.0.
// 


/// <remarks/>
// CODEGEN: 'http://schemas.xmlsoap.org/ws/2004/09/policy' ad alanındaki 'Policy' isteğe bağlı WSDL uzantı öğesi işlenmedi.
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name = "ZAPP_EBA_FATURA_ONAY_RFC", Namespace = "urn:sap-com:document:sap:rfc:functions")]
public partial class ZAPP_EBA_FATURA_ONAY_RFC : System.Web.Services.Protocols.SoapHttpClientProtocol
{

    private System.Threading.SendOrPostCallback CallZAPP_EBA_FATURA_ONAY_RFCOperationCompleted;

    /// <remarks/>
    public ZAPP_EBA_FATURA_ONAY_RFC()
    {
        this.Url = "http://SMPERPPRDA1.sampadc.local:8000/sap/bc/srt/rfc/sap/zapp_eba_fatura_onay_rfc" +
            "/400/zapp_eba_fatura_onay_rfc/zapp_eba_fatura_onay_rfc";
    }

    /// <remarks/>
    public event CallZAPP_EBA_FATURA_ONAY_RFCCompletedEventHandler CallZAPP_EBA_FATURA_ONAY_RFCCompleted;

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:rfc:functions:ZAPP_EBA_FATURA_ONAY_RFC:ZAPP_EBA_FATURA_O" +
        "NAY_RFCRequest", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("ZAPP_EBA_FATURA_ONAY_RFCResponse", Namespace = "urn:sap-com:document:sap:rfc:functions")]
    public ZAPP_EBA_FATURA_ONAY_RFCResponse CallZAPP_EBA_FATURA_ONAY_RFC([System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:sap-com:document:sap:rfc:functions")] ZAPP_EBA_FATURA_ONAY_RFC1 ZAPP_EBA_FATURA_ONAY_RFC)
    {
        object[] results = this.Invoke("CallZAPP_EBA_FATURA_ONAY_RFC", new object[] {
                    ZAPP_EBA_FATURA_ONAY_RFC});
        return ((ZAPP_EBA_FATURA_ONAY_RFCResponse)(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginCallZAPP_EBA_FATURA_ONAY_RFC(ZAPP_EBA_FATURA_ONAY_RFC1 ZAPP_EBA_FATURA_ONAY_RFC, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("CallZAPP_EBA_FATURA_ONAY_RFC", new object[] {
                    ZAPP_EBA_FATURA_ONAY_RFC}, callback, asyncState);
    }

    /// <remarks/>
    public ZAPP_EBA_FATURA_ONAY_RFCResponse EndCallZAPP_EBA_FATURA_ONAY_RFC(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((ZAPP_EBA_FATURA_ONAY_RFCResponse)(results[0]));
    }

    /// <remarks/>
    public void CallZAPP_EBA_FATURA_ONAY_RFCAsync(ZAPP_EBA_FATURA_ONAY_RFC1 ZAPP_EBA_FATURA_ONAY_RFC)
    {
        this.CallZAPP_EBA_FATURA_ONAY_RFCAsync(ZAPP_EBA_FATURA_ONAY_RFC, null);
    }

    /// <remarks/>
    public void CallZAPP_EBA_FATURA_ONAY_RFCAsync(ZAPP_EBA_FATURA_ONAY_RFC1 ZAPP_EBA_FATURA_ONAY_RFC, object userState)
    {
        if ((this.CallZAPP_EBA_FATURA_ONAY_RFCOperationCompleted == null))
        {
            this.CallZAPP_EBA_FATURA_ONAY_RFCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCallZAPP_EBA_FATURA_ONAY_RFCOperationCompleted);
        }
        this.InvokeAsync("CallZAPP_EBA_FATURA_ONAY_RFC", new object[] {
                    ZAPP_EBA_FATURA_ONAY_RFC}, this.CallZAPP_EBA_FATURA_ONAY_RFCOperationCompleted, userState);
    }

    private void OnCallZAPP_EBA_FATURA_ONAY_RFCOperationCompleted(object arg)
    {
        if ((this.CallZAPP_EBA_FATURA_ONAY_RFCCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.CallZAPP_EBA_FATURA_ONAY_RFCCompleted(this, new CallZAPP_EBA_FATURA_ONAY_RFCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    public new void CancelAsync(object userState)
    {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:sap-com:document:sap:rfc:functions")]
public partial class ZAPP_EBA_FATURA_ONAY_RFC1
{

    private ZEBA_INV_APPROVL[] iT_INVOICEField;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    public ZEBA_INV_APPROVL[] IT_INVOICE
    {
        get
        {
            return this.iT_INVOICEField;
        }
        set
        {
            this.iT_INVOICEField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:sap-com:document:sap:rfc:functions")]
public partial class ZEBA_INV_APPROVL
{

    private string mANDTField;

    private string idField;

    private string vBELNField;

    private string eBA_REFField;

    private string sTATUField;

    private string aPPR_USERField;

    private string aPPR_DATEField;

    private System.DateTime? aPPR_TIMEField;

    private string aPPR_DATE_TIMEField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MANDT
    {
        get
        {
            return this.mANDTField;
        }
        set
        {
            this.mANDTField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ID
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string VBELN
    {
        get
        {
            return this.vBELNField;
        }
        set
        {
            this.vBELNField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string EBA_REF
    {
        get
        {
            return this.eBA_REFField;
        }
        set
        {
            this.eBA_REFField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string STATU
    {
        get
        {
            return this.sTATUField;
        }
        set
        {
            this.sTATUField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string APPR_USER
    {
        get
        {
            return this.aPPR_USERField;
        }
        set
        {
            this.aPPR_USERField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string APPR_DATE
    {
        get
        {
            return this.aPPR_DATEField;
        }
        set
        {
            this.aPPR_DATEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "time")]
    public System.DateTime? APPR_TIME
    {
        get
        {
            return this.aPPR_TIMEField;
        }
        set
        {
            this.aPPR_TIMEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string APPR_DATE_TIME
    {
        get
        {
            return this.aPPR_DATE_TIMEField;
        }
        set
        {
            this.aPPR_DATE_TIMEField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:sap-com:document:sap:rfc:functions")]
public partial class ZAPP_EBA_FATURA_ONAY_RFCResponse
{

    private ZEBA_INV_APPROVL[] iT_INVOICEField;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    public ZEBA_INV_APPROVL[] IT_INVOICE
    {
        get
        {
            return this.iT_INVOICEField;
        }
        set
        {
            this.iT_INVOICEField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
public delegate void CallZAPP_EBA_FATURA_ONAY_RFCCompletedEventHandler(object sender, CallZAPP_EBA_FATURA_ONAY_RFCCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CallZAPP_EBA_FATURA_ONAY_RFCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal CallZAPP_EBA_FATURA_ONAY_RFCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public ZAPP_EBA_FATURA_ONAY_RFCResponse Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((ZAPP_EBA_FATURA_ONAY_RFCResponse)(this.results[0]));
        }
    }
}
