//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.8.3928.0.
// 


/// <remarks/>
// CODEGEN: 'http://schemas.xmlsoap.org/ws/2004/09/policy' ad alanındaki 'Policy' isteğe bağlı WSDL uzantı öğesi işlenmedi.
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="ZEBA_GET_FAT", Namespace="urn:sap-com:document:sap:rfc:functions")]
public partial class ZEBA_GET_FAT : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback ZEBA_F_MUHASEB_ENTGOperationCompleted;
    
    /// <remarks/>
    public ZEBA_GET_FAT() {
        this.Url = "http://SMPPRDJOB1.sampadc.local:8000/sap/bc/srt/rfc/sap/zeba_get_fatura/400/zeba_" +
            "get_fat/zeba_get_fat";
    }
    
    /// <remarks/>
    public event ZEBA_F_MUHASEB_ENTGCompletedEventHandler ZEBA_F_MUHASEB_ENTGCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:rfc:functions:ZEBA_GET_FATURA:ZEBA_F_MUHASEB_ENTGRequest" +
        "", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("ZEBA_F_MUHASEB_ENTGResponse", Namespace="urn:sap-com:document:sap:rfc:functions")]
    public ZEBA_F_MUHASEB_ENTGResponse ZEBA_F_MUHASEB_ENTG([System.Xml.Serialization.XmlElementAttribute("ZEBA_F_MUHASEB_ENTG", Namespace="urn:sap-com:document:sap:rfc:functions")] ZEBA_F_MUHASEB_ENTG ZEBA_F_MUHASEB_ENTG1) {
        object[] results = this.Invoke("ZEBA_F_MUHASEB_ENTG", new object[] {
                    ZEBA_F_MUHASEB_ENTG1});
        return ((ZEBA_F_MUHASEB_ENTGResponse)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginZEBA_F_MUHASEB_ENTG(ZEBA_F_MUHASEB_ENTG ZEBA_F_MUHASEB_ENTG1, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("ZEBA_F_MUHASEB_ENTG", new object[] {
                    ZEBA_F_MUHASEB_ENTG1}, callback, asyncState);
    }
    
    /// <remarks/>
    public ZEBA_F_MUHASEB_ENTGResponse EndZEBA_F_MUHASEB_ENTG(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((ZEBA_F_MUHASEB_ENTGResponse)(results[0]));
    }
    
    /// <remarks/>
    public void ZEBA_F_MUHASEB_ENTGAsync(ZEBA_F_MUHASEB_ENTG ZEBA_F_MUHASEB_ENTG1) {
        this.ZEBA_F_MUHASEB_ENTGAsync(ZEBA_F_MUHASEB_ENTG1, null);
    }
    
    /// <remarks/>
    public void ZEBA_F_MUHASEB_ENTGAsync(ZEBA_F_MUHASEB_ENTG ZEBA_F_MUHASEB_ENTG1, object userState) {
        if ((this.ZEBA_F_MUHASEB_ENTGOperationCompleted == null)) {
            this.ZEBA_F_MUHASEB_ENTGOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZEBA_F_MUHASEB_ENTGOperationCompleted);
        }
        this.InvokeAsync("ZEBA_F_MUHASEB_ENTG", new object[] {
                    ZEBA_F_MUHASEB_ENTG1}, this.ZEBA_F_MUHASEB_ENTGOperationCompleted, userState);
    }
    
    private void OnZEBA_F_MUHASEB_ENTGOperationCompleted(object arg) {
        if ((this.ZEBA_F_MUHASEB_ENTGCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.ZEBA_F_MUHASEB_ENTGCompleted(this, new ZEBA_F_MUHASEB_ENTGCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
public partial class ZEBA_F_MUHASEB_ENTG {
    
    private ZEBA_T_MUHKAYIT[] iT_EBANRField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public ZEBA_T_MUHKAYIT[] IT_EBANR {
        get {
            return this.iT_EBANRField;
        }
        set {
            this.iT_EBANRField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
public partial class ZEBA_T_MUHKAYIT {
    
    private string mANDTField;
    
    private string zEBASNOField;
    
    private string iNVNOField;
    
    private string rEFNOField;
    
    private string mATNRField;
    
    private string eRDATField;
    
    private string kUNNRField;
    
    private decimal nETWRField;
    
    private string wAERKField;
    
    private decimal tOTALField;
    
    private string b_STATUSField;
    
    private string gDATEField;
    
    private string gUZEITField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MANDT {
        get {
            return this.mANDTField;
        }
        set {
            this.mANDTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ZEBASNO {
        get {
            return this.zEBASNOField;
        }
        set {
            this.zEBASNOField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string INVNO {
        get {
            return this.iNVNOField;
        }
        set {
            this.iNVNOField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string REFNO {
        get {
            return this.rEFNOField;
        }
        set {
            this.rEFNOField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MATNR {
        get {
            return this.mATNRField;
        }
        set {
            this.mATNRField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ERDAT {
        get {
            return this.eRDATField;
        }
        set {
            this.eRDATField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string KUNNR {
        get {
            return this.kUNNRField;
        }
        set {
            this.kUNNRField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal NETWR {
        get {
            return this.nETWRField;
        }
        set {
            this.nETWRField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string WAERK {
        get {
            return this.wAERKField;
        }
        set {
            this.wAERKField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal TOTAL {
        get {
            return this.tOTALField;
        }
        set {
            this.tOTALField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string B_STATUS {
        get {
            return this.b_STATUSField;
        }
        set {
            this.b_STATUSField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string GDATE {
        get {
            return this.gDATEField;
        }
        set {
            this.gDATEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string GUZEIT {
        get {
            return this.gUZEITField;
        }
        set {
            this.gUZEITField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
public partial class ZEBA_F_MUHASEB_ENTGResponse {
    
    private string mESSAGESField;
    
    private string rESULTField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MESSAGES {
        get {
            return this.mESSAGESField;
        }
        set {
            this.mESSAGESField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RESULT {
        get {
            return this.rESULTField;
        }
        set {
            this.rESULTField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
public delegate void ZEBA_F_MUHASEB_ENTGCompletedEventHandler(object sender, ZEBA_F_MUHASEB_ENTGCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ZEBA_F_MUHASEB_ENTGCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal ZEBA_F_MUHASEB_ENTGCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public ZEBA_F_MUHASEB_ENTGResponse Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((ZEBA_F_MUHASEB_ENTGResponse)(this.results[0]));
        }
    }
}
