//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.8.3928.0.
// 


/// <remarks/>
// CODEGEN: 'http://schemas.xmlsoap.org/ws/2004/09/policy' ad alanındaki 'Policy' isteğe bağlı WSDL uzantı öğesi işlenmedi.
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name = "ZQDMS_CUST_SUP_RFC", Namespace = "urn:sap-com:document:sap:rfc:functions")]
public partial class ZQDMS_CUST_SUP_RFC : System.Web.Services.Protocols.SoapHttpClientProtocol
{

    private System.Threading.SendOrPostCallback CallZQDMS_CUST_SUP_RFCOperationCompleted;

    /// <remarks/>
    public ZQDMS_CUST_SUP_RFC()
    {
        this.Url = "http://SMPERPPRDA1.sampadc.local:8000/sap/bc/srt/rfc/sap/zqdms_cust_sup_rfc/400/z" +
            "qdms_cust_sup_rfc/zqdms_cust_sup_rfc";
    }

    /// <remarks/>
    public event CallZQDMS_CUST_SUP_RFCCompletedEventHandler CallZQDMS_CUST_SUP_RFCCompleted;

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:rfc:functions:ZQDMS_CUST_SUP_RFC:ZQDMS_CUST_SUP_RFCReque" +
        "st", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("ZQDMS_CUST_SUP_RFCResponse", Namespace = "urn:sap-com:document:sap:rfc:functions")]
    public ZQDMS_CUST_SUP_RFCResponse CallZQDMS_CUST_SUP_RFC([System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:sap-com:document:sap:rfc:functions")] ZQDMS_CUST_SUP_RFC1 ZQDMS_CUST_SUP_RFC)
    {
        object[] results = this.Invoke("CallZQDMS_CUST_SUP_RFC", new object[] {
                    ZQDMS_CUST_SUP_RFC});
        return ((ZQDMS_CUST_SUP_RFCResponse)(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginCallZQDMS_CUST_SUP_RFC(ZQDMS_CUST_SUP_RFC1 ZQDMS_CUST_SUP_RFC, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("CallZQDMS_CUST_SUP_RFC", new object[] {
                    ZQDMS_CUST_SUP_RFC}, callback, asyncState);
    }

    /// <remarks/>
    public ZQDMS_CUST_SUP_RFCResponse EndCallZQDMS_CUST_SUP_RFC(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((ZQDMS_CUST_SUP_RFCResponse)(results[0]));
    }

    /// <remarks/>
    public void CallZQDMS_CUST_SUP_RFCAsync(ZQDMS_CUST_SUP_RFC1 ZQDMS_CUST_SUP_RFC)
    {
        this.CallZQDMS_CUST_SUP_RFCAsync(ZQDMS_CUST_SUP_RFC, null);
    }

    /// <remarks/>
    public void CallZQDMS_CUST_SUP_RFCAsync(ZQDMS_CUST_SUP_RFC1 ZQDMS_CUST_SUP_RFC, object userState)
    {
        if ((this.CallZQDMS_CUST_SUP_RFCOperationCompleted == null))
        {
            this.CallZQDMS_CUST_SUP_RFCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCallZQDMS_CUST_SUP_RFCOperationCompleted);
        }
        this.InvokeAsync("CallZQDMS_CUST_SUP_RFC", new object[] {
                    ZQDMS_CUST_SUP_RFC}, this.CallZQDMS_CUST_SUP_RFCOperationCompleted, userState);
    }

    private void OnCallZQDMS_CUST_SUP_RFCOperationCompleted(object arg)
    {
        if ((this.CallZQDMS_CUST_SUP_RFCCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.CallZQDMS_CUST_SUP_RFCCompleted(this, new CallZQDMS_CUST_SUP_RFCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    public new void CancelAsync(object userState)
    {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:sap-com:document:sap:rfc:functions")]
public partial class ZQDMS_CUST_SUP_RFC1
{

    private ZQDMS_STR_SUPL_CUST_ADD[] e_LISTField;

    private ZQDMS_STR_SUPL_BANKA[] e_LIST_BNKField;

    private ZQDMS_STR_ZTERM[] e_LIST_ZTERMField;

    private string iV_BUKRSField;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    public ZQDMS_STR_SUPL_CUST_ADD[] E_LIST
    {
        get
        {
            return this.e_LISTField;
        }
        set
        {
            this.e_LISTField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    public ZQDMS_STR_SUPL_BANKA[] E_LIST_BNK
    {
        get
        {
            return this.e_LIST_BNKField;
        }
        set
        {
            this.e_LIST_BNKField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    public ZQDMS_STR_ZTERM[] E_LIST_ZTERM
    {
        get
        {
            return this.e_LIST_ZTERMField;
        }
        set
        {
            this.e_LIST_ZTERMField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IV_BUKRS
    {
        get
        {
            return this.iV_BUKRSField;
        }
        set
        {
            this.iV_BUKRSField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:sap-com:document:sap:rfc:functions")]
public partial class ZQDMS_STR_SUPL_CUST_ADD
{

    private string kUNNRField;

    private string nAME1Field;

    private string iSYERI_KODUField;

    private string zTERMField;

    private string tURUField;

    private string aDRESField;

    private string tEL_NUMBERField;

    private string tEL_EXTENSField;

    private string fAX_NUMBERField;

    private string sMTP_ADDRField;

    private string sICILNOField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string KUNNR
    {
        get
        {
            return this.kUNNRField;
        }
        set
        {
            this.kUNNRField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NAME1
    {
        get
        {
            return this.nAME1Field;
        }
        set
        {
            this.nAME1Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ISYERI_KODU
    {
        get
        {
            return this.iSYERI_KODUField;
        }
        set
        {
            this.iSYERI_KODUField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ZTERM
    {
        get
        {
            return this.zTERMField;
        }
        set
        {
            this.zTERMField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TURU
    {
        get
        {
            return this.tURUField;
        }
        set
        {
            this.tURUField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ADRES
    {
        get
        {
            return this.aDRESField;
        }
        set
        {
            this.aDRESField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TEL_NUMBER
    {
        get
        {
            return this.tEL_NUMBERField;
        }
        set
        {
            this.tEL_NUMBERField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TEL_EXTENS
    {
        get
        {
            return this.tEL_EXTENSField;
        }
        set
        {
            this.tEL_EXTENSField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FAX_NUMBER
    {
        get
        {
            return this.fAX_NUMBERField;
        }
        set
        {
            this.fAX_NUMBERField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SMTP_ADDR
    {
        get
        {
            return this.sMTP_ADDRField;
        }
        set
        {
            this.sMTP_ADDRField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SICILNO
    {
        get
        {
            return this.sICILNOField;
        }
        set
        {
            this.sICILNOField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:sap-com:document:sap:rfc:functions")]
public partial class ZQDMS_STR_ZTERM
{

    private string zTERMField;

    private string tEXT1Field;

    private string sPRASField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ZTERM
    {
        get
        {
            return this.zTERMField;
        }
        set
        {
            this.zTERMField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TEXT1
    {
        get
        {
            return this.tEXT1Field;
        }
        set
        {
            this.tEXT1Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SPRAS
    {
        get
        {
            return this.sPRASField;
        }
        set
        {
            this.sPRASField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:sap-com:document:sap:rfc:functions")]
public partial class ZQDMS_STR_SUPL_BANKA
{

    private string kUNNRField;

    private string wAERSField;

    private string bANKAField;

    private string bRNCHField;

    private string iBANField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string KUNNR
    {
        get
        {
            return this.kUNNRField;
        }
        set
        {
            this.kUNNRField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string WAERS
    {
        get
        {
            return this.wAERSField;
        }
        set
        {
            this.wAERSField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BANKA
    {
        get
        {
            return this.bANKAField;
        }
        set
        {
            this.bANKAField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BRNCH
    {
        get
        {
            return this.bRNCHField;
        }
        set
        {
            this.bRNCHField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IBAN
    {
        get
        {
            return this.iBANField;
        }
        set
        {
            this.iBANField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:sap-com:document:sap:rfc:functions")]
public partial class ZQDMS_CUST_SUP_RFCResponse
{

    private ZQDMS_STR_SUPL_CUST_ADD[] e_LISTField;

    private ZQDMS_STR_SUPL_BANKA[] e_LIST_BNKField;

    private ZQDMS_STR_ZTERM[] e_LIST_ZTERMField;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    public ZQDMS_STR_SUPL_CUST_ADD[] E_LIST
    {
        get
        {
            return this.e_LISTField;
        }
        set
        {
            this.e_LISTField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    public ZQDMS_STR_SUPL_BANKA[] E_LIST_BNK
    {
        get
        {
            return this.e_LIST_BNKField;
        }
        set
        {
            this.e_LIST_BNKField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    public ZQDMS_STR_ZTERM[] E_LIST_ZTERM
    {
        get
        {
            return this.e_LIST_ZTERMField;
        }
        set
        {
            this.e_LIST_ZTERMField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
public delegate void CallZQDMS_CUST_SUP_RFCCompletedEventHandler(object sender, CallZQDMS_CUST_SUP_RFCCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CallZQDMS_CUST_SUP_RFCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal CallZQDMS_CUST_SUP_RFCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public ZQDMS_CUST_SUP_RFCResponse Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((ZQDMS_CUST_SUP_RFCResponse)(this.results[0]));
        }
    }
}
